# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8723ddd2ff4e56e8baed599763da5bc68c5e25a82a77cd3cbb04c4e0e9cc77746632147824eb90cb2f5788f6edd42b39c5e0b0735acb1bd48e6f03c0a99a8bf9

test:
  secret_key_base: b2da758092d9aae7bd20edfa5cd49ae57a307ce9bb7fe1293c90997a8c873714bdd840b5f8a01bde03f3ad579bc48b4d9f2f268ccceaab39fb186ac706d3b11c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
